name: Mera CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code lo GitHub se
        uses: actions/checkout@v3

      - name: Node.js setup karo
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: App test karo
        run: node app.js &

      - name: Docker image banao
        run: docker build -t mera-cicd-image .
